version: "3.9"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: primdev
      MYSQL_PASSWORD: primdev
      MYSQL_DATABASE: primdev
      MYSQL_ROOT_PASSWORD: primdev
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080